export default [
    {
        name: 'landing',
        title: 'Cайт-визитка',
        orderText: 'сайт-визитку',
        description: 'Простой сайт до 25 страниц с описанием вашего бизнеса',
        price: 5000,
    },
    {
        name: 'website',
        title: 'Cайт',
        orderText: 'сайт',
        description: `Сайт с уникальным шаблоном и функционалом,
        разработанный специально для вас`,
        price: 15000,
    },
    {
        name: 'shop',
        title: 'Интернет-магазин',
        orderText: 'интернет-магазин',
        description: 'Продавайте товары через интернет',
        price: 20000,
    },
    {
        name: 'web-design',
        title: 'Веб-дизайн',
        orderText: 'веб-дизайн',
        description: 'Разработаем дизайн для сайта',
        price: 3000,
    },
    {
        name: 'exe',
        title: 'Программа под Windows',
        orderText: 'программу под Windows',
        description: `Устанавливается на компьютер пользователя`,
        price: 10000,
    },
    {
        name: 'bot',
        title: 'Чат-бот',
        orderText: 'чат-бот',
        description: `Чат-бот для Telegram или ВКонтакте позволит вашим клиентам
        быстро заказать услугу, уточнить информацию и многое другое`,
        price: 4000,
    },
    {
        name: 'pr',
        title: 'Digital-продвижение, PR',
        orderText: 'digital-продвижение, PR',
        description: `Прорекламируем ваш бизнес в интернете`,
        price: 1000,
    },
    {
        name: 'android-app',
        title: 'Приложение под Android',
        orderText: 'приложение под Android',
        description: `Разработаем программу под самую популярную мобильную платформу`,
        price: 10000,
    },
    {
        name: 'support',
        title: 'Техподдержка',
        orderText: 'техподдержку',
        description: `Наполнение и доработка сайта, хостинг, продление домена и многое другое`,
        price: 8000,
    },
    {
        name: 'other',
        title: 'Другое',
        orderText: 'другую услугу',
        description: `Опишите, что вы хотите получить`,
        price: 'Цена договорная',
    },
];
